#!/usr/bin/env python3
"""Does the misspecification detector actually detect anything?

The project has claimed throughout that importance-sampling efficiency doubles
as a check on the model: feed it a spectrum the model cannot explain and the
efficiency collapses, so the method fails loudly rather than returning a tight
wrong answer. That claim has never been tested. Every observation the pipeline
has ever seen was generated by the same simulator that the inference uses, so
the model has always been exactly right.

This script generates observations by processes the inference model
*structurally cannot reproduce*, and asks two questions of each:

1. **Is the answer still right?**  Does the 95% interval on J_CH still contain
   the truth, and how far does the point estimate move?
2. **Does anything warn you?**  Two candidate detectors are measured: the
   importance-sampling efficiency, and a goodness-of-fit test on the residuals
   at the best-fit point (chi-square against its own degrees of freedom).

Three misspecifications, chosen because each is a thing that actually happens
in a ZULF experiment:

``equivalence``
    Two protons that the model treats as magnetically equivalent are not
    quite: J_CH becomes J+delta and J-delta. This is the situation Wilzewski
    et al. invoke to explain their benzaldehyde discrepancy, where residual
    dipolar couplings are "difficult to distinguish from J-couplings". The
    parameterization by symmetry class cannot represent it at any theta.

``drift``
    The residual field changes during acquisition. Each line sweeps, so the
    observed spectrum is the average over the excursion: positions shift and
    lines broaden. The model has one T2 for every line, so it can absorb a
    uniform broadening but not a differential one.

``axis_scale``
    The frequency axis is mis-calibrated by a factor 1+eps. Every measured
    frequency is wrong by the same *relative* amount. This one is included
    because it is predicted to be invisible: see ``degeneracy_check``.

Run ``python misspecification.py`` for the full study, or
``python misspecification.py --quick`` for a smoke test.
"""

from __future__ import annotations

import numpy as np
from scipy import stats

import zulf_forward as zf
import zulf_infer as zi
import results

SEED = 0

#: (kind, system, levels). Levels are in the natural unit of each effect.
CASES = [
    # Levels chosen after measuring the response: breaking the equivalence
    # antisymmetrically is *quadratic* in the summary, not linear, because the
    # XA2 line sits at 3/2 times the mean coupling and the antisymmetric part
    # first enters at second order. 0.001 Hz moves the summary by 5e-6 of the
    # noise; 2 Hz moves it by 18. So the interesting range is of order 1 Hz,
    # which is also the scale of a real residual dipolar coupling.
    ("equivalence", "formaldehyde", [0.0, 0.1, 0.25, 0.5, 1.0, 2.0]),
    ("drift",       "formic_acid",  [0.0, 0.05, 0.1, 0.2, 0.5, 1.0]),
    ("axis_scale",  "formic_acid",  [0.0, 1e-6, 3e-6, 1e-5, 3e-5, 1e-4]),
]

#: Tag and simulation count of the cached network for each system, matching
#: train_library.py exactly so this study loads them instead of retraining.
NETS = {"formic_acid":  dict(tag="formic_acid_150k", n_sims=150_000),
        "formaldehyde": dict(tag="formaldehyde_60k", n_sims=60_000)}


# ---------------------------------------------------------------------------
# generating data the model cannot fit
# ---------------------------------------------------------------------------
def _summary(prob, f, a, width_hz):
    """Peak summary at the problem's own instrument resolution."""
    return zi.peak_summary(f, a, width_hz, prob.J_center,
                           n_low=prob.n_low, n_high=prob.n_high,
                           merge_hz=prob.merge_hz)


def clean_lines(prob, theta):
    """The line list the inference model itself would produce at ``theta``."""
    Jm = prob.J_matrix(theta)
    B_nT, ang, T2 = (float(v) for v in theta[prob.n_couplings:])
    B = zf.field_vector(B_nT * 1e-3, ang)
    f, a = zf.line_list(prob.sys, B=B, J=Jm)
    return f, a, 1.0 / (np.pi * T2)


def gen_equivalence(prob, theta, delta_hz, n_sub=None):
    """Break the equivalence of two protons the model insists are identical.

    ``prob.J_matrix`` fills every pair in a coupling class with one value.
    Here the first pair of the J_CH class gets J+delta and the second J-delta,
    so the mean coupling is unchanged and no value of theta reproduces it.
    """
    Jm = prob.J_matrix(theta)
    pairs = prob.classes[0][1]
    if len(pairs) < 2:
        raise ValueError("equivalence test needs a class with >= 2 pairs")
    (i0, j0), (i1, j1) = pairs[0], pairs[1]
    Jm[i0, j0] = Jm[j0, i0] = Jm[i0, j0] + delta_hz
    Jm[i1, j1] = Jm[j1, i1] = Jm[i1, j1] - delta_hz
    B_nT, ang, T2 = (float(v) for v in theta[prob.n_couplings:])
    B = zf.field_vector(B_nT * 1e-3, ang)
    f, a = zf.line_list(prob.sys, B=B, J=Jm)
    return _summary(prob, f, a, 1.0 / (np.pi * T2))


def gen_drift(prob, theta, drift_nT, n_sub=9):
    """The residual field sweeps by ``drift_nT`` over the acquisition.

    The observed spectrum is the time average, so each line is smeared over
    the range its frequency covers. Lines are accumulated over the excursion
    and merged, which moves the reported positions; the extra broadening is
    added in quadrature to the model linewidth, which is what an experimenter
    fitting the spectrum would report.
    """
    Jm = prob.J_matrix(theta)
    B_nT, ang, T2 = (float(v) for v in theta[prob.n_couplings:])
    w0 = 1.0 / (np.pi * T2)
    if drift_nT == 0:
        f, a, _ = clean_lines(prob, theta)
        return _summary(prob, f, a, w0)

    offs = np.linspace(-0.5 * drift_nT, 0.5 * drift_nT, n_sub)
    fs, amps, spread = [], [], []
    per_step = []
    for d in offs:
        B = zf.field_vector(max(B_nT + d, 1e-6) * 1e-3, ang)
        f, a = zf.line_list(prob.sys, B=B, J=Jm)
        per_step.append((f, a))
        fs.append(f)
        amps.append(a / n_sub)
    # How far the strong lines actually travelled: that is the extra width.
    ref_f, ref_a = per_step[0]
    end_f, _ = per_step[-1]
    if len(ref_f) == len(end_f) and len(ref_f):
        w = np.abs(ref_a)
        if w.sum() > 0:
            spread = float(np.average(np.abs(end_f - ref_f), weights=w))
        else:
            spread = float(np.mean(np.abs(end_f - ref_f)))
    else:
        spread = 0.0
    width = float(np.hypot(w0, spread))
    return _summary(prob, np.concatenate(fs), np.concatenate(amps), width)


def gen_axis_scale(prob, theta, eps, n_sub=None):
    """Every measured frequency is wrong by the same relative amount."""
    f, a, w0 = clean_lines(prob, theta)
    return _summary(prob, f * (1.0 + eps), a, w0 * (1.0 + eps))


GENERATORS = {"equivalence": gen_equivalence, "drift": gen_drift,
              "axis_scale": gen_axis_scale}


def generate(prob, theta, kind, level, rng=None):
    """One misspecified observation, with the problem's own noise added."""
    x = GENERATORS[kind](prob, theta, level)
    if rng is not None:
        x = x + rng.normal(0.0, prob.slot_sigmas())
    return x


# ---------------------------------------------------------------------------
# the two candidate detectors
# ---------------------------------------------------------------------------
def goodness_of_fit(prob, x_obs, theta_fit):
    """Chi-square of the residuals at the best fit, and its p-value.

    The noise is Gaussian with known scale, so at the true model the summed
    squared residual follows chi-square with ``x_dim - n_params`` degrees of
    freedom. This is the classical test and it needs no network at all; it is
    included because it is the obvious thing to compare the efficiency against.
    """
    mu = prob.simulate_one(theta_fit, noisy=False)
    r = (np.asarray(x_obs, float) - mu) / prob.slot_sigmas()
    chi2 = float(np.sum(r * r))
    dof = max(len(r) - len(theta_fit), 1)
    return chi2, dof, float(stats.chi2.sf(chi2, dof))


def diagnose(prob, posterior, x_obs, theta_true, seed=0, n_post=4000):
    """Run the standard pipeline on one observation and score it."""
    import torch
    import local_baseline as lb

    with zi.torch_seed(seed):
        s = posterior.sample((n_post,),
                             x=torch.as_tensor(x_obs, dtype=torch.float32),
                             show_progress_bars=False).numpy()
    w, eff = zi.importance_reweight(prob, posterior, x_obs, s)
    lo, hi = zi.weighted_quantile(s[:, 0], [0.025, 0.975], w)
    mean = float(np.average(s[:, 0], weights=w))

    fit = lb.local_fit(prob, x_obs, 0.5 * (prob.low + prob.high))
    chi2, dof, p = goodness_of_fit(prob, x_obs, fit["theta"])

    return dict(
        efficiency=float(eff),
        width_mHz=float((hi - lo) * 1e3),
        bias_mHz=float((mean - theta_true[0]) * 1e3),
        covered=bool(lo <= theta_true[0] <= hi),
        chi2=chi2, dof=dof, p_value=p,
        fit_J_bias_mHz=float((fit["theta"][0] - theta_true[0]) * 1e3),
    )


# ---------------------------------------------------------------------------
# the analytic check on the axis-scale case
# ---------------------------------------------------------------------------
def degeneracy_check(prob, theta, eps=1e-5):
    """Is a frequency-scale error absorbed exactly by rescaling the parameters?

    A multiplet line sits at c*J for a fixed c, the low-frequency line scales
    with the field, and the reported width is 1/(pi*T2). So scaling every
    frequency by 1+eps should be reproduced by J -> J(1+eps), B -> B(1+eps),
    T2 -> T2/(1+eps). If that holds, no residual is left for any detector to
    find, and the only consequence is a J biased by eps with full confidence.

    Returns the largest mismatch between the two summaries, in units of the
    measurement noise on each slot.
    """
    x_scaled = gen_axis_scale(prob, theta, eps)
    theta2 = np.array(theta, float).copy()
    theta2[:prob.n_couplings] *= (1.0 + eps)
    theta2[prob.n_couplings] *= (1.0 + eps)          # |B|
    theta2[-1] /= (1.0 + eps)                        # T2
    x_model = prob.simulate_one(theta2, noisy=False)
    resid = (x_scaled - x_model) / prob.slot_sigmas()
    return float(np.max(np.abs(resid))), theta2


# ---------------------------------------------------------------------------
def run(quick=False):
    n_rep = 2 if quick else 6
    n_post = 1500 if quick else 4000
    rows = []
    store = {}

    for kind, system, levels in CASES:
        if quick:
            levels = [levels[0], levels[-1]]
        prob = zi.InferenceProblem(system=system, seed=SEED)
        print(f"\n{'=' * 84}\n{kind}  ({system}, {len(levels)} levels x "
              f"{n_rep} repeats)\n{'=' * 84}", flush=True)
        net = NETS[system]
        posterior, _ = zi.train_or_load(prob, tag=net["tag"],
                                        n_sims=net["n_sims"], seed=SEED,
                                        max_num_epochs=150)
        theta_true = 0.5 * (prob.low + prob.high)
        theta_true[0] = prob.J_center + 0.7
        if prob.n_couplings > 1:
            theta_true[1] = 0.0

        print(f"{'level':>10} {'covered':>9} {'bias mHz':>10} {'width mHz':>10} "
              f"{'eff':>8} {'chi2/dof':>9} {'p':>10}")
        for lev in levels:
            reps = []
            for r in range(n_rep):
                rng = np.random.default_rng(1000 + r)
                x = generate(prob, theta_true, kind, lev, rng)
                reps.append(diagnose(prob, posterior, x, theta_true,
                                     seed=SEED + r, n_post=n_post))
            agg = dict(
                kind=kind, system=system, level=float(lev),
                coverage=float(np.mean([d["covered"] for d in reps])),
                bias_mHz=float(np.mean([d["bias_mHz"] for d in reps])),
                width_mHz=float(np.mean([d["width_mHz"] for d in reps])),
                efficiency=float(np.mean([d["efficiency"] for d in reps])),
                chi2_per_dof=float(np.mean([d["chi2"] / d["dof"] for d in reps])),
                p_value=float(np.median([d["p_value"] for d in reps])),
            )
            rows.append(agg)
            print(f"{lev:>10.3g} {agg['coverage']:>9.2f} {agg['bias_mHz']:>10.2f} "
                  f"{agg['width_mHz']:>10.2f} {agg['efficiency']:>8.1%} "
                  f"{agg['chi2_per_dof']:>9.2f} {agg['p_value']:>10.2g}",
                  flush=True)

        if kind == "axis_scale":
            resid, _ = degeneracy_check(prob, theta_true, eps=1e-5)
            print(f"\n  degeneracy check: rescaling (J, |B|, T2) reproduces a "
                  f"1e-5 axis error\n  to within {resid:.2g} sigma on the worst "
                  f"slot (1.0 would be one noise unit)")
            store["axis_degeneracy_sigma"] = resid

    return rows, store


def main(argv=None):
    import sys
    quick = "--quick" in (argv if argv is not None else sys.argv[1:])
    rows, extra = run(quick=quick)
    if quick:
        print("\n(quick mode: nothing recorded)")
        return 0

    summary = {}
    for kind, _, _ in CASES:
        sub = [r for r in rows if r["kind"] == kind]
        base, worst = sub[0], sub[-1]
        summary[kind] = dict(
            worst_level=worst["level"],
            coverage_at_worst=worst["coverage"],
            bias_at_worst_mHz=worst["bias_mHz"],
            efficiency_clean=base["efficiency"],
            efficiency_at_worst=worst["efficiency"],
            efficiency_ratio=worst["efficiency"] / max(base["efficiency"], 1e-12),
            p_value_at_worst=worst["p_value"],
            chi2_per_dof_at_worst=worst["chi2_per_dof"],
        )
    summary.update(extra)
    results.record("misspecification", summary)
    np.savez("misspecification.npz",
             **{k: np.array([r[k] for r in rows]) for k in
                ("level", "coverage", "bias_mHz", "width_mHz", "efficiency",
                 "chi2_per_dof", "p_value")},
             kind=np.array([r["kind"] for r in rows]))
    print("\nwrote misspecification.npz and recorded to results.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
